---
apiVersion: v1
kind: Secret
metadata:
  name: harping-pig-grafana
  # namespace: istio-system
  labels:
    app: grafana
type: Opaque
data:
  # username: YWRtaW4=
  # passphrase: MWYyZDFlMmU2N2Rm
  admin-user: YWRtaW4=
  admin-password: MWYyZDFlMmU2N2Rm
