apiVersion: v1
kind: Service
metadata:
  name: quarkus-kafka-keda-processor
  # namespace: techtalksns
spec:
  # type: NodePort
  type: LoadBalancer
  ports:
    - port: 80
  # - port: 8088
  selector:
    run: quarkus-kafka-keda
