apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-kafka-producer
  namespace: kafka
  labels:
    app.kubernetes.io: quarkus-kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io: quarkus-kafka-producer
  template:
    metadata:
      labels:
        app.kubernetes.io: quarkus-kafka-producer
    spec:
      containers:
        - name: quarkus-kafka-producer
          image: localhost:32000/quarkus-kafka-producer
          imagePullPolicy: Always
